version: "3"
services:

  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://db:5432/poll
    networks:
      - poll-tier

  redis:
    restart: always
    image: "redis:7"
    ports:
      - '6379'
    networks:
      - poll-tier
      - back-tier
  
  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://db:5432/worker
    networks:
      - back-tier
  
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_DB=poll
      - POSTGRES_USR=admin
      - POSTGRES_PASSWORD=adminpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
  
  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://db:5432/result
    networks:
      - result-tier
  
networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: